"""MANAGER AGENT - understands the request, builds an analysis plan,
and coordinates the other agents.

The Manager never performs the analysis itself; it plans, assigns,
tracks, and routes corrections. Plan is structured JSON.
"""

from __future__ import annotations

import json
import logging

from backend.agents.base import AgentContext, ToolPlanAgent
from backend.models import AnalysisPlan, AgentResult
from backend.utils.errors import LLMError

logger = logging.getLogger("analyst.agents")

AGENT_ROSTER = {
    "cleaner": "Data quality inspection (always used).",
    "analyst": "Business/statistical analysis of the user question.",
    "visualizer": "Generate supporting charts when the data supports them.",
}

MANAGER_PLAN_MAX = 6


class ManagerAgent:
    """Pure coordinator. Produces plans + correction assignments."""

    name = "manager"
    label = "Manager Agent"

    def __init__(self, llm=None):
        self.llm = llm

    async def create_plan(self, ctx: AgentContext) -> AnalysisPlan:
        """Understand the goal and return a structured task plan."""
        if self.llm is not None:
            try:
                data = await self.llm.chat_json(
                    system=(
                        "You are the MANAGER agent in a multi-agent data analysis team. "
                        "You plan the work, you do not do the work. "
                        "Always include cleaner and analyst. Include visualizer only when "
                        "the dataset can produce meaningful charts."
                    ),
                    user=self._plan_prompt(ctx),
                    validator=self._plan_validator,
                    temperature=0.15,
                    max_tokens=700,
                    max_attempts=2,
                )
                return AnalysisPlan(**data)
            except LLMError as exc:
                logger.warning("Manager LLM failed (%s); using heuristic plan.", exc)
        return self.heuristic_plan(ctx)

    def heuristic_plan(self, ctx: AgentContext) -> AnalysisPlan:
        profile = ctx.profile or {}
        overview = profile.get("overview", {})
        columns = [str(c) for c in overview.get("column_names", [])]
        dtypes = overview.get("dtypes", {})
        numeric = [c for c in columns if "float" in str(dtypes.get(c)) or "int" in str(dtypes.get(c))]
        dates = columns and "date" in " ".join(columns).lower()

        tasks = [{"agent": "cleaner", "task": "Inspect data quality", "priority": "high"}]
        tasks.append({"agent": "analyst", "task": "Analyze the dataset and answer: " + ctx.question, "priority": "high"})
        if numeric:
            viz = "Create charts for the most important findings"
            if dates:
                viz += " (include a trend if possible)"
            tasks.append({"agent": "visualizer", "task": viz, "priority": "medium"})
        return AnalysisPlan(
            objective=ctx.question,
            tasks=tasks,
            notes="Heuristic plan generated by Manager.",
        )

    def correction_tasks(self, directives: list[dict]) -> list[dict]:
        """Convert Reviewer directives into correction tasks."""
        tasks = []
        for d in directives[:5]:
            agent = d.get("agent")
            if agent not in AGENT_ROSTER:
                continue
            tasks.append({
                "agent": agent,
                "task": f"Correct the following issue: {d.get('instruction')}",
                "priority": "high",
                "correction": True,
            })
        return tasks

    def _plan_prompt(self, ctx: AgentContext) -> str:
        return f"""You are the MANAGER. A user uploaded a dataset and asked:
"{ctx.question}"

Dataset profile:
{ctx.profile_text}

Available specialist agents:
{json.dumps(AGENT_ROSTER)}

Decide which agents are required and what each should do. Note:
- Never do the analysis yourself - always delegate.
- Cleaner and Analyst are usually required.
- Visualizer is only useful if there are numeric columns.
Return strict JSON:
{{"objective": "restate the user goal",
 "tasks": [
   {{"agent": "cleaner", "task": "...", "priority": "high"}},
   {{"agent": "analyst", "task": "...", "priority": "high"}},
   {{"agent": "visualizer", "task": "...", "priority": "medium"}}
 ],
 "notes": "plan rationale"}}
Max {MANAGER_PLAN_MAX} tasks."""

    def _plan_validator(self, data):
        if not isinstance(data, dict):
            raise ValueError("Plan must be an object.")
        tasks = data.get("tasks")
        if not isinstance(tasks, list) or not tasks:
            raise ValueError("Plan needs at least one task.")
        valid_agents = set(AGENT_ROSTER)
        cleaned = []
        seen = set()
        for t in tasks[:MANAGER_PLAN_MAX]:
            if not isinstance(t, dict):
                continue
            agent = t.get("agent")
            if agent not in valid_agents or agent in seen:
                continue
            seen.add(agent)
            cleaned.append({
                "agent": agent,
                "task": str(t.get("task") or f"Work on {agent}"),
                "priority": str(t.get("priority") or "medium"),
            })
        if not cleaned:
            raise ValueError("No valid tasks in plan.")
        return {
            "objective": str(data.get("objective") or ""),
            "tasks": cleaned,
            "notes": str(data.get("notes") or ""),
        }