"""VISUALIZATION AGENT - decides *which* charts help and generates them.

The LLM picks chart types and columns; the backend executes the chart
tools and returns saved filenames. Only meaningful charts are built.
"""

from __future__ import annotations

import json

from backend.agents.base import AgentContext, ToolPlanAgent, findings_validator
from backend.tools.registry import try_execute_tool

CHART_TOOLS = """- create_bar_chart(x_column, y_column|None, agg: sum|mean|count, title, x_label, y_label)
  Compare categories.
- create_line_chart(x_column, y_column, agg, title, x_label, y_label)
  Trends over time / ordered axis.
- create_histogram(column, bins, title)
  Distribution of one numeric column.
- create_scatter_plot(x_column, y_column, title)
  Relationship between two numeric columns.
- create_box_plot(y_column, x_column|None, title)
  Distribution, optional per group.
- create_heatmap(columns, title)
  Correlation heatmap."""

DEFAULT_CHART_OPS = [
    None,  # filled by heuristic
]


class VisualizationAgent(ToolPlanAgent):
    name = "visualizer"
    label = "Visualization Agent"
    max_operations = 6
    interpret_max_tokens = 1200
    plan_max_tokens = 700

    def build_plan_prompt(self, ctx: AgentContext) -> str:
        analyst_insights = ""
        prior = ctx.prior_results.get("analyst")
        if prior:
            analyst_insights = json.dumps(prior.output, default=str)[:1500]

        return f"""You are the VISUALIZATION agent. Decide which charts actually help
answer the user's question, then request them via tools.

User question: {ctx.question}
Analyst findings (what to illustrate):
{analyst_insights}

Dataset profile:
{ctx.profile_text}

Available chart tools:
{CHART_TOOLS}

Guidelines:
- Create at most 4 charts. Only charts that support the analysis.
- Prefer group-by and time-series charts that match the Analyst's findings.
- Validate column names against the dataset profile.
- Pie charts: avoid unless a single category breakdown truly helps.

Return strict JSON:
{{"reasoning": "...",
 "operations": [
   {{"tool": "create_bar_chart",
     "arguments": {{"x_column":"Region","y_column":"Sales","agg":"sum","title":"Sales by Region","x_label":"Region","y_label":"Sales"}},
     "reason": "why this chart"}}
 ]}}"""

    def build_interpret_prompt(self, ctx: AgentContext, tool_outcomes: list[dict]) -> str:
        compact = json.dumps(tool_outcomes, default=str, ensure_ascii=False)
        return f"""You are the VISUALIZATION agent. The following charts were actually
generated by Python (each result has a filename and title).

Chart generation results:
{compact}

Return strict JSON:
{{"findings": [
   {{"title": "Interpretation of chart",
     "detail": "what the chart shows",
     "evidence": "chart filename + the numbers behind it",
     "severity": "info"}}
 ],
 "summary": "one-line chart summary",
 "confidence": 0.0-1.0}}"""

    def validate_interpret(self, data):
        return findings_validator(data)

    def default_plan(self, ctx: AgentContext) -> dict:
        return {"operations": _heuristic_chart_plan(ctx)}

    def deterministic_result(self, ctx: AgentContext) -> dict:
        findings = []
        charts = []
        for op in self.default_plan(ctx)["operations"]:
            outcome = try_execute_tool(ctx.df, op["tool"], op["arguments"])
            if not outcome["ok"]:
                continue
            res = outcome["result"]
            charts.append(res)
            findings.append({
                "title": f"Chart: {res.get('title')}",
                "detail": res.get("reason", "Chart generated."),
                "evidence": res.get("relative_path", ""),
                "severity": "info",
            })
        if not charts:
            return {
                "findings": [{
                    "title": "No charts generated",
                    "detail": "No suitable chart configuration found.",
                    "evidence": "chart planning",
                    "severity": "info",
                }],
                "charts": [],
                "summary": "No charts generated.",
                "confidence": 0.5,
            }
        return {
            "findings": findings,
            "charts": charts,
            "summary": f"Generated {len(charts)} charts.",
            "confidence": 0.85,
            "notes": "Deterministic fallback charts.",
        }

    def postprocess(self, ctx: AgentContext, output: dict, outcomes: list[dict]) -> dict:
        charts = []
        for outcome in outcomes:
            if outcome.get("ok") and isinstance(outcome.get("result"), dict):
                chart = outcome["result"]
                if chart.get("relative_path"):
                    charts.append(chart)
        output["charts"] = charts
        return output


def _heuristic_chart_plan(ctx: AgentContext) -> list[dict]:
    """Choose charts from the profile and analyst findings."""
    profile = ctx.profile or {}
    overview = profile.get("overview", {})
    columns = [str(c) for c in overview.get("column_names", [])]
    dtypes = overview.get("dtypes", {})
    info = profile.get("columns", {})
    unique_cols = {
        item["column"]: item.get("unique_count", 0)
        for item in profile.get("unique_counts", {}).get("columns", [])
    }

    numeric = [c for c in columns if "float" in str(dtypes.get(c)) or "int" in str(dtypes.get(c))]
    dates = [c for c in columns if "date" in c.lower() or "date" in str(dtypes.get(c)).lower()]

    def cat_cols():
        return [
            c
            for c in columns
            if c not in (numeric + dates)
            and 2 <= unique_cols.get(c, 999) <= 60
        ]

    ops = []
    cats = cat_cols()
    value = numeric[0] if numeric else None

    # bar: top group comparison on first categorical
    if cats and value:
        ops.append({
            "tool": "create_bar_chart",
            "arguments": {"x_column": cats[0], "y_column": value, "agg": "sum",
                          "title": f"{value} by {cats[0]}", "x_label": cats[0], "y_label": value},
            "reason": "Compare performance across categories",
        })
    elif cats and len(cats) >= 1:
        ops.append({
            "tool": "create_bar_chart",
            "arguments": {"x_column": cats[0], "title": f"Distribution of {cats[0]}", "x_label": cats[0], "y_label": "count"},
            "reason": "Understand category distribution",
        })

    # line: trend
    if dates and value:
        ops.append({
            "tool": "create_line_chart",
            "arguments": {"x_column": dates[0], "y_column": value, "agg": "sum",
                          "title": f"{value} over time", "x_label": dates[0], "y_label": value},
            "reason": "Show trend over time",
        })

    # scatter: relationship between first two numerics
    if len(numeric) >= 2:
        ops.append({
            "tool": "create_scatter_plot",
            "arguments": {"x_column": numeric[0], "y_column": numeric[1],
                          "title": f"{numeric[0]} vs {numeric[1]}", "x_label": numeric[0], "y_label": numeric[1]},
            "reason": "Visualize relationship between numeric columns",
        })

    # box: distribution of the primary metric
    if value:
        ops.append({
            "tool": "create_box_plot",
            "arguments": {"y_column": value, "x_column": cats[0] if cats else None,
                          "title": f"Distribution of {value}" + (f" by {cats[0]}" if cats else ""),
                          "y_label": value},
            "reason": "Show spread and outliers",
        })

    # heatmap: correlations
    if len(numeric) >= 3:
        ops.append({
            "tool": "create_heatmap",
            "arguments": {"columns": None, "title": "Correlation Heatmap"},
            "reason": "Summarize numeric relationships",
        })

    return ops[:4]